name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential
      
      - name: Create directories
        run: |
          mkdir -p build
          mkdir -p docs
          mkdir -p src/templates
      
      - name: Build
        run: |
          cd build
          cmake ..
          make
          
      - name: Generate site
        run: |
          cd build
          ./directory_browser .. -o ../docs
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
